### ISSUE TITLE
Please remove my analytics script

### ISSUE THREAD

**Issue by wezm** [sdkal-club/sdkal-club.github.io#3]
Hi, I'm glad my website template was helpful in building yours but you've included my analytics script in the layout, which means hits to your site show up in my analytics (GoatCounter).

If you could remove this script it would be most appreciated:

https://github.com/sdkal-club/sdkal-club.github.io/blob/d8ef3c368b0c44cc591dddbc46caebaad9ba7111/templates/layout.html#L19

**Comment by MingcongBai** [comment]
Ah, sorry. I will address it right now. This issue will be closed automatically with a fix.

**Comment by MingcongBai** [comment]
@wezm All done, sorry about that.

**Comment by wezm** [comment]
Great thanks 👍 Looks like the deploy failed though.

**Comment by MingcongBai** [comment]
Uh oh... Looking into it now. Thanks for the note.

**Comment by RedL0tus** [comment]
@wezm 
> Great thanks +1 Looks like the deploy failed though.

![image](https://user-images.githubusercontent.com/16459559/149715218-c02107a1-d2b6-4f17-bbd8-53e1725a3eb4.png)

And it failed in a mysterious way... I've just manually triggered a re-run, it werks this time.
